name: build

on:
  push:
    branches: [ "dev", "main" ]

  workflow_dispatch:
    inputs:
      minify:
        description: "Minify JavaScript"
        required: true
        default: true
        type: boolean

jobs:
  build-plugin:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        plugin-name:
          - rara-maps

    env:
      MINIFY: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.minify == 'false' && ''
               || '1' }}
      node-version: 24.7.0
      plugin-path: ./plugins/${{ matrix.plugin-name }}

    defaults:
      run:
        working-directory: ${{ env.plugin-path }}
    
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
        cache-dependency-path: '${{ env.plugin-path }}/package-lock.json'
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
