name: build

on:
  push:
    branches: [ "dev", "main" ]

  workflow_dispatch:
    inputs:
      minify:
        description: "Minify JavaScript"
        required: true
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      node-version: 24.7.0
      WEBPACK_MINIFY: ${{ github.event_name == 'workflow_dispatch'
                          && github.event.inputs.minify == 'false'
                          && ''
                       || '1' }}
    
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm ci
    - run: npm run build --workspaces
    - run: npm run lint --workspaces
    - run: ls ./plugins/rara-maps/build/
    - uses: actions/upload-artifact@v4
      with:
        path: |
          ./plugins/rara-maps/build/*

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
    - uses: actions/checkout@v5
    - run: ls -R
    - uses: actions/download-artifact@v5
    - run: ls -R
    - run: ./scripts/deploy.sh origin deploy-${{ env.BRANCH_NAME }} --push
