name: build

on:
  push:
    branches: [ "dev", "main" ]

  workflow_dispatch:
    inputs:
      minify:
        description: "Minify JavaScript"
        required: true
        default: true
        type: boolean

jobs:
  build-plugin:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        plugin-name:
          - rara-maps

    env:
      node-version: 24.7.0
      plugin-path: ./plugins/${{ matrix.plugin-name }}
      WEBPACK_MINIFY: ${{ github.event_name == 'workflow_dispatch'
                          && github.event.inputs.minify == 'false'
                          && ''
                       || '1' }}

    defaults:
      run:
        working-directory: ${{ env.plugin-path }}
    
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
        cache-dependency-path: '${{ env.plugin-path }}/package-lock.json'
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.plugin-name }}-build
        path: ${{ env.plugin-path }}/build

  deploy:
    runs-on: ubuntu-latest
    needs: build-plugin

    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      COMMIT: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v5
    - uses: actions/download-artifact@v4
      with:
        name: rara-maps-build
        path: ./plugins/rara-maps/build
    - run: ./scripts/deploy.sh ${{ env.BRANCH_NAME }} ${{ env.COMMIT }}
